### ISSUE TITLE
Other locations of BOWTIE2 mapping of 450k probes 

### ISSUE THREAD

**Issue by YoannPa** [sirselim/illumina450k_filtering#1]
Dear sirselim, 
Do you have any additionnal file listing locations where the multiple alignments happened for the BOWTIE2 mapping of 450k probes ?
Something in Bed-like format:  

**probeID | chr | start | end**
cg00000658 | 1 | 15454 | 15500
cg00000658 | 7 | 457851 | 457900
                        **...**

I would be very interested in it if you could add it.
Thank you for making available this repository.

Best regards.

**Comment by sirselim** [comment]
That's not something that I have, but it is something that is very easy to generate in theory. I've added it as a Feature Request.

Is there a particular reason you require a bed file of these probes?

**Comment by YoannPa** [comment]
Hi,  

I would prefer a bed-like file (tab separated essentially, with as many column as necessary), simply because the table-like format is more convenient for me load and parse. But if you have another suggestion that makes more sense to you, I am open to it.
That would be super useful.

**Comment by sirselim** [comment]
OK, I've created and added a "bed" file for the multi-mapped probes. There are several caveats:
* I left a header in there so people know exactly what is in each column
  * it is structured as per bed file rules, so delete the header and you're away
* I wrote a small script to infer the positions, it may or may not be completely accurate
  * I used strand to infer the direction
  * I then either added or subtracted 51bp (source sequence length) based on the strand to create both start and end positions for each CpG site in the multi-mapped file

I'm going to call this closed for now, but might revisit in the future if it's deemed useful (i.e. is a bed file for all probes useful to anyone?).

**Comment by YoannPa** [comment]
Hi @sirselim ,
Thank you very much for adding this file ! I haven't go through all of it, but to me the content of it sounds clear and contains all necessary information.
This will be super helpful for me !

May I ask for your full name and affiliation in case I want to cite you ?

Best, Yoann.
