### ISSUE TITLE
This is great. How do we cite this? 

### ISSUE THREAD

**Issue by ahdee** [sirselim/illumina450k_filtering#5]
I would like to cite this. Is there a reference?

**Comment by sirselim** [comment]
Thanks for wanting to acknowledge the work I did on this. I only have the GitHub repository, there are no research articles etc. which you could cite. However, I have added the option to cite the repository. You can get this from the repository front page by selecting "Cite this repository". The below image shows where this is.

<img width="1310" alt="image" src="https://github.com/sirselim/illumina450k_filtering/assets/5932864/b05fab5c-7464-45da-9f05-0ea54956cef7">

Thanks again!

**Comment by ahdee** [comment]
perfect thank you.
